### PR TITLE
rework; 0.7 compatibility

### PR DESCRIPTION
**Pull request by rbeer**
Maybe I've overdone it, but I couldn't find code handling plugin images in src/plugins.js, src/plugins/, at first glance.

There's still one issue, though: When the gallery opens, all images are deleted from the DOM. I don't know jQuery that much; updating fancybox might help. I'll look into it.

Correction: Only the clicked image is deleted; but scrolling through images (in the lightbox) doesn't work.

### CODE REVIEW

**Comment by psychobunny** [comment]
Is that issue a current problem, or introduced by your PR? (I'm on a train right now can't test)

**Comment by rbeer** [comment]
Current problem. I just double checked by reseting to c5d2272 (your last, "0.0.6").
I didn't touch the plugins public .js - yet so it seems. :)

**Comment by rbeer** [comment]
Alright:
There is some node removal going on in fancybox and it seems to have its purpose, at some point. 
But I noticed some other things, while looking into it:
  * Fancybox is kinda outdated and poorly maintained. (Last commit 7 months ago, 342 open issues without much attention to them).
  * For the purpose of this plugin it seems also pretty bloated. Support for HTML, youtube, etc. isn't really needed here, is it?
  * There are way smaller (faster) lightbox solutions.
  * **Most importantly**, [fancybox's license](http://creativecommons.org/licenses/by-nc/3.0/) doesn't permit commercial use!

At this point, I'm heavily tempted to just drop fancybox all together and replace it with another jQuery plugin from their 7 pages long listing. I'd sift through that and pick a more suited solution, if you're ok with that.

**Comment by rbeer** [comment]
Changes:
 * Dropped fancybox in favor of https://github.com/blueimp/Gallery.
 * Images are added on infinite scroll loading. Both when overlay is open or closed.
 * rbeer/nodebb-plugin-gallery@b47a4d8 diverts from originial blueimp/Gallery. Just doesn't seem to offer preparing the instance.

And yes; I've overdone it by moving the images manually to public/images. :stuck_out_tongue_winking_eye:

**Pull request closed without merging**
